name: add & commit test

on: gollum

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: run main
      run: docker build -t foobar . && docker run -e INSTAGRAM_USERNAME=$INSTAGRAM_USERNAME -e LINE_NOTIFY_ACCESS_TOKEN=$LINE_NOTIFY_ACCESS_TOKEN -v $PWD:/ foobar
      env:
        LINE_NOTIFY_ACCESS_TOKEN: ${{ secrets.LINE_NOTIFY_ACCESS_TOKEN }}
        INSTAGRAM_USERNAME: kyanny
    
    - uses: EndBug/add-and-commit@v4
      with:
        add: 'timestamp.txt'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
