name: add & commit test

on: gollum

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo $(date) > date.txt
    
    - name: run main
      run: env && docker build -t foobar . && docker run foobar
      env:
#        LINE_NOTIFY_ACCESS_TOKEN: ${{ secrets.LINE_NOTIFY_ACCESS_TOKEN }}
        INSTAGRAM_USERNAME: kyanny
    
    - uses: EndBug/add-and-commit@v4
      with:
        add: 'date.txt'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
